# Generated by Django 4.1.6 on 2023-02-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_kilometerpoint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="Nom de l'évènement")),
                ('description', models.CharField(max_length=140, verbose_name="Description de l'évènement")),
                ('date', models.DateTimeField(verbose_name="Date de l'évènement")),
                ('kilometer_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.kilometerpoint', verbose_name="Point kilométrique lié a l'évènement")),
            ],
            options={
                'verbose_name': 'Évènement',
                'verbose_name_plural': 'Évènements',
            },
        ),
    ]
