# Generated by Django 4.1.6 on 2023-02-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom du projet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom du trajet')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Projet lié')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom de la voie')),
                ('routes', models.ManyToManyField(to='project.route', verbose_name='Route liée')),
            ],
            options={
                'verbose_name': 'Voie',
                'verbose_name_plural': 'Voies',
            },
        ),
        migrations.CreateModel(
            name='KilometerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom du Point Kilometrique')),
                ('tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.track', verbose_name='Voie liée')),
            ],
            options={
                'verbose_name': 'Point kilometrique',
                'verbose_name_plural': 'Points kilometriques',
            },
        ),
    ]
